spring:
  application:
    name: mybatis-generator
  datasource:
    url: jdbc:mysql://192.168.186.128:3306/xxl_job
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Onlyyouroo@@@
