spring:
  cloud:
    function:
      location: ${basedir}/target/it/bootapp/target/bootapp-1.0.0.RELEASE-exec.jar
      #location: maven://org.designer:designer-function-simple:1.0.0-RELEASE
      #function-class: org.designer.function.provider.Provider
      routing-expression: /function
      web:
        path: '/function'
        export:
          sink:
            content-type: 'application/json'
    stream:
      bindings:
        #默认
        input:
          group: default_group
          content-type: text/plain
        #默认
        output:
          group: default_group
          content-type: text/plain
          producer:
            required-groups: default_p_group
      binders:
        test:
          type: rocketmq
          environment:
            'k': 'v'
          inheritEnvironment: true
          defaultCandidate: true
      #rocketmq binder
      rocketmq:
        binder:
          group: default_p_group
  devtools:
    restart:
      additional-exclude: